### ISSUE TITLE
The "comment" keyword in the code makes the next code color the same as the actual comment color.

### ISSUE THREAD

**Issue by MubeenMurj** [Shopify/theme-check-vscode#109]
The code color becomes the same as the actual comment's code color after using the "comment" keyword. 

![image](https://user-images.githubusercontent.com/20734612/211016741-79b2b944-e14a-4f43-8906-11ebf57c80ea.png)

**Comment by haroldao** [comment]
@MubeenMurj you may have the Liquid extension called "Liquid" by Panoply installed 👀 ...
