### ISSUE TITLE
formatOnSave doesn't appear to fix wrapping and whitespace issues when liquid is within quotes or capture tag

### ISSUE THREAD

**Issue by alibosworth** [Shopify/theme-check-vscode#119]
I searched existing issues in theme-check-vscode and theme-check and couldn't find this, but apologies if it is somewhere and I failed to find it.

We're finding that formatOnSave is not working for a render tag within quotes, like this:

<img width="886" alt="Screen Shot 2023-03-10 at 11 55 44 AM" src="https://user-images.githubusercontent.com/63747/224415146-d4268a98-a950-4fb0-b32f-19676c2adb95.png">

It also appears not to work if within a capture tag like this:

<img width="893" alt="Screen Shot 2023-03-10 at 11 52 11 AM" src="https://user-images.githubusercontent.com/63747/224414519-c5c45a64-a8e9-477d-a09d-282264256ba1.png">

if it is outside of either of these situations like this:

<img width="916" alt="Screen Shot 2023-03-10 at 11 52 31 AM" src="https://user-images.githubusercontent.com/63747/224414601-33d3eed4-a9f1-4b3e-b76a-b2049f167a9f.png">

then upon save it is "correctly" autoformatted to be like this:

<img width="642" alt="Screen Shot 2023-03-10 at 11 53 03 AM" src="https://user-images.githubusercontent.com/63747/224414687-6db28527-a5c5-4bb6-a7b3-9690030122cb.png">

My hunch is this is a problem with a theme-check rule, however when I disable `  "editor.formatOnSave": false,
` in VSC and run theme-check on this code, it doesn't raise an issue with any 3 of these scenarios, so I'm opening the issue on the VSC plugin directly.  I'm happy to re-report this in a more appropriate place if someone can point me in the right direction

**Comment by mgmanzella** [comment]
possibly related https://github.com/Shopify/theme-tools/issues/190

**Comment by mgmanzella** [comment]
if this is still an issue please open an issue in the [theme tools repo](https://github.com/Shopify/theme-tools), this repo is no longer the source of truth 🙏 thank you!
