### ISSUE TITLE
What's the suggested VS Code configuration for this extension?

### ISSUE THREAD

**Issue by brady-sewall** [Shopify/theme-check-vscode#130]
Specifically:
- Does it conflict with other Shopify related extensions?
- Should the stand-alone Prettier extension be removed because it's bundled with this extension? Or can Prettier run side-by-side but ignore the files the Shopify extension is formatting? I've noticed formatting on save can cause behavior I didn't expect, like a closing span ">" going to a new line.
- Does VS Code need any configuration for auto-formatting or auto-completion?

**Comment by jamesmengo** [comment]
👋🏻 This repo has been moved to https://github.com/Shopify/theme-tools

If this is still an issue, please open a new issue there with the tag area:theme-check-vscode
