### ISSUE TITLE
Latest update has really annoying feature, formats spacing on save

### ISSUE THREAD

**Issue by twilson90** [Shopify/theme-check-vscode#138]
The formatting makes no sense and is extremely annoying.

`{% capture current %}{% cycle 1, 2 %}{% endcapture %}`

Becomes:
```
{% capture current %}
    {% cycle 1, 2 %}{% endcapture %}
```

And

`<a class="slide-link" href="{{ link_url }}" title="{{ alt | escape }}"></a>`

Becomes:
```
<a
    class="slide-link"
    href="{{ link_url }}"
    title="{{ alt | escape }}"></a>
```

I can't save changes in VS Code without this happening.

**Comment by charlespwd** [comment]
This comes from a different extension. The prettier plugin we use has unit tests that show this shouldn't be happening:

https://github.com/Shopify/prettier-plugin-liquid/compare/test/vscode-138?expand=1

You can also try it out in the playground for yourself.

https://shopify.github.io/prettier-plugin-liquid/
https://screenshot.click/04-07-7kl41-5t3cu.mp4
