### ISSUE TITLE
[Bug] Theme check does not work inside a monorepo directory structure

### ISSUE THREAD

**Issue by AdiRishi** [Shopify/theme-check-vscode#141]
## The problem

The theme check plugin is unable to handle themes not existing at a top level directory. A common example of this is in a monorepo setup (e.g when using turborepo).
I've made an example repository to demonstrate this - https://github.com/AdiRishi/shopify-theme-check-bug

When you open the repository at it's root, and navigate to let's say `shopify/themes/bohemian-vibe-theme/snippets/article-card.liquid` then you see a lot of errors like `Undefined object media_aspect_ratio` (just one example)
However, if you were to open just the `bohemian-vibe-theme` in vscode (aka this folder as root) then the errors don't show up.

From what I can tell, this is because the `shopify theme check` command is not being run at the template root, and the CLI command itself does not handle being run at a location that is not the template root.

## Potential solution

I am fairly new to the shopify ecosystem, but here are some options
- Only run the `theme check` command in folders which have a `.theme-check.yml` file
- Allow users to configure which folders theme check is run on

Let me know if any more information is needed.

**Comment by AdiRishi** [comment]
Okay, update on this. You can get around this problem by adding a `.theme-check.yml` file to the root of the monorepo and setting the `root` property to the directory location of your shopify theme. E.g.
```yml
root: shopify/themes/custom-theme
```

However, this wouldn't work if you had multiple themes in a single monorepo. So the issue is still valid.

**Comment by charlespwd** [comment]
Acknowledged. Already fixed soon in future version of language server. Stay tuned for release.
