### ISSUE TITLE
Formatting .liquid files clears the code instead

### ISSUE THREAD

**Issue by Afamsinachi** [Shopify/theme-check-vscode#150]
Hello, I've setup everything as mentioned in developing theme docs, but formatting .liquid files clears code instead of formatting the document. I'm having this experience on vscode, prettier-plugin-liquid 1.4.1, prettier 3.2.4. 

**.prettierrc**
`{
  "printWidth": 120,
  "singleQuote": true,
  "tabWidth": 2,
  "useTabs": false,
  "plugins": ["@shopify/prettier-plugin-liquid"],
  "overrides": [
    {
      "files": "*.liquid",
      "options": {
        "singleQuote": false
      }
    }
  ]
}`

**Comment by gregbarbosa** [comment]
Facing the same issue here, not sure how to debug to share more details.

**Comment by charlespwd** [comment]
See Shopify/theme-tools#327

**Comment by gregbarbosa** [comment]
In case anyone else finds this: try reinstalling yarn. 

I had a conflict somewhere with my homebrew and yarn installs. Uninstalling yarn completely and re-downloading threw brew worked!
