### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by we5** [Shopify/theme-check-vscode#31]
Hi,

I installed it according to the documentation for macOS.
I also deactivated all other extensions providing liquid snippets or completion.

If i open or create a .liquid file no code or tag completion happens.
What am i doing wrong? :)

**Comment by dhmacs** [comment]
Same here, nobody on my team was able to get this up and running 🤔

**Comment by charlespwd** [comment]
Hiya 👋, if you open a terminal and run the following command, what's the output?

```
which shopify && shopify version
```

Did you see an error or warning notification when opening a liquid file?

**Comment by dhmacs** [comment]
@charlespwd I got this:

```
/usr/local/bin/shopify
2.0.1
```

I found out that the linting part of the plugin is working, as I get some warnings from theme-check. But I'm not able to get the indentation/formatting working

**Comment by we5** [comment]
@charlespwd for me it is also:
```
/usr/local/bin/shopify
2.0.1
```

Also i got the linting errors in the editor but the rest is not working.

**Comment by charlespwd** [comment]
Ugh:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/4990691/124485856-fde00e00-dd7a-11eb-9cde-a48ec6c10d08.png">

**Comment by we5** [comment]
Ok, I just uninstalled all other liquid/Shopify extensions and recorded another video (before i just deactivated them, so this time i made sure nothing is there). I also always restarted VSCode.

What I found out is, that the global objects and helpers are shown, and also the filters.

So, it seems, objects are working, but not control/iteration/theme tags or the like.

https://user-images.githubusercontent.com/1068/124488146-cdff2d80-ddaf-11eb-97d2-13665fa3e6bf.mov

**Comment by charlespwd** [comment]
>but not control/iteration/theme tags or the like.

What do you mean precisely? I'm not sure I understand 😓 

* `{% for <cmd-space>`, or
* `{% if <cmd-space>`, or
* `{% if product.<cmd-space>`, or

In the first case, it would be because it's the location for a variable. `{% for product in <cmd_space>` _should_ give a list of objects. If it doesn't, that's a bug.

In the second case, it _should_ complete global objects there. If it doesn't, that's a bug.

In the third case, that's WIP (need to export types from our core code base and it's a lot of work 😅)

Or is it something else?

**Comment by we5** [comment]
> > Or did you expect a snippet for `if/endif` and for `for $var in $vars/endfor`?
> 
> Yeah I thought it was broken because I expected control/iteration/theme tags to add the closing tag (similar to emmet), but I guess it's not included

me too 🙈

**Comment by diegovogel** [comment]
@charlespwd the demo video on [this page](https://marketplace.visualstudio.com/items?itemName=Shopify.theme-check-vscode) mentions "Auto closing pairs" and it shows a `for` snippet being auto completed. Is that a feature or not?

**Comment by charlespwd** [comment]
I think the video is ambiguous and conveys the impression that it completes control flow tags in pairs.

Auto closing pairs in this context is meant to show that brackets are automatically closing. So:
* `{ }`
* `{% %}`
* `{{ }}`
* etc.

And for the tag completion, we're showing `for` and `form` as those are the only two options in the language.

But we're sending the wrong impression that we're closing the control flow tag. That's a problem and I see it now. I opened the above issue in theme-check to remove that confusion.

**Comment by marksawmillcreative** [comment]
Ah, ok thanks for clarifying. 

@we5 and @dhmacs , [this extension](https://marketplace.visualstudio.com/items?itemName=sissel.shopify-liquid) will autocomplete tag snippets. And you don't even need to type the opening brackets.

**Comment by we5** [comment]
> Ah, ok thanks for clarifying.
> 
> @we5 and @dhmacs , [this extension](https://marketplace.visualstudio.com/items?itemName=sissel.shopify-liquid) will autocomplete tag snippets. And you don't even need to type the opening brackets.

Thanks, in fact I had this installed before but disabled it for testing this extension in an isolated way ;)
