### ISSUE TITLE
Prettier plugin

### ISSUE THREAD

**Issue by dhmacs** [Shopify/theme-check-vscode#32]
It would be awesome if this integrates with prettier to format files with correct indentation. Having to manually indent liquid files is one of the major pain when developing a Shopify theme

**Comment by charlespwd** [comment]
Agreed. 

Anyone else reading this, don't hesititate to +1 the above comment. We should put this on our radar.

**Comment by ronnross** [comment]
> There is an existing extension just called [Liquid](https://marketplace.visualstudio.com/items?itemName=sissel.shopify-liquid) that has formatting built in using PrettyDiff. Would this be that difficult to add to this extension?

Looks like development has stall for that extension, and it doesn't seem to help with code formatting in its present state. I'm still looking forward to offical shopify support.

**Comment by petercampanelli** [comment]
It helps with formatting, but it definitely is buggy and doesn't support newer features or Liquid in JS or CSS. I switched away from it, but really am missing some of the functionality.

**Comment by pveen2** [comment]
+1

**Comment by duffpop** [comment]
Huge +1

**Comment by charlespwd** [comment]
I'm locking the conversation. It's on our radar folks. 

There's a prototype in the pipeline but also a lot of edge cases to worry about.

**Comment by charlespwd** [comment]
It exists :D

- https://github.com/shopify/prettier-plugin-liquid
- https://www.npmjs.com/package/@shopify/prettier-plugin-liquid
