### ISSUE TITLE
Check only liquid files changed

### ISSUE THREAD

**Issue by tomaszs** [Shopify/theme-check-vscode#60]
Currently, when I save a liquid file, the extension validates all liquid files in the project. It is time-consuming.
It might have been changed to test only liquid file that I have changed.

**Comment by charlespwd** [comment]
Hey there, this issue has been reported before. The gist is that some checks require the entire theme to run (unused translations, required files, etc.) We're skipping the ones that are not, but the progress bar gives you the impression that we're not. 

There are performance improvements we can and will do. Closing this in favour of the other issue in Shopify/theme-check
