### ISSUE TITLE
Comment tags randomly causing everything after it to highlight as comment, even after endcomment

### ISSUE THREAD

**Issue by peepers-rick** [Shopify/theme-check-vscode#68]
Since yesterday's release I'm having an issue where the comment syntax highlighting is not ending after a `{%- comment -%}` tag. Meaning, everything after an `{%- endcomment -%}` still highlights as a comment. It never happens without the whitespace control, so I never run into the bug when using `{% comment %}` and `{% endcomment %}`  but it happens _most_ (not all) of the time when I use `{%- comment -%}`/`{%- endcomment -%}` or `{%- comment %}`/`{% endcomment -%}`.

Attaching a screenshot where you can see it happening once and not happening another time all in the same file.

![liquid-syntax-comment-issue](https://user-images.githubusercontent.com/98047278/153475379-48d7bf7a-3365-4593-a154-611d7b8758d3.jpeg)

**Comment by charlespwd** [comment]
Thanks for the report. I'll get right on that.

**Comment by charlespwd** [comment]
Should be fixed in v1.3.5. Deploying right now, should make it to your editor in 5-10min :)
