### ISSUE TITLE
Command 'Liquid Theme Check: Run Checks' resulted in an error (Language client is not ready yet)

### ISSUE THREAD

**Issue by vfonic** [Shopify/theme-check-vscode#70]
I started getting new error as of today. I have no idea why.

When I open a Shopify project (Shopify theme git repo), the Shopify Liquid language client doesn't start anymore.

If I try to manually run `Liquid Theme Check: Run Checks`, this is the error I get:
> Command 'Liquid Theme Check: Run Checks' resulted in an error (Language client is not ready yet)

`Liquid Theme Check: Restart Server` shows no output and nothing changes. When running `Liquid Theme Check: Run Checks`, I get the same error like above.

How can I debug this in order to fix it?
I don't have the "Theme check" in the "Output" pane dropdown anymore, as if the extension is disabled altogether (but it's not).
I disabled and enabled the extension, but that didn't change anything.

Any help would be appreciated. 🙏

**Comment by vfonic** [comment]
After an hour or so of debugging, the error went away. I haven't really discovered why.

I'm closing this now and will reopen if this happens again and I figure out more details.

**Comment by charlespwd** [comment]
You can use the following for instance:

```
# works with relative paths
extend: ../.theme-check.yml

# or absolute path
extend: /path/to/.theme-check.yml
```

**Comment by vfonic** [comment]
Oh, so I found a solution:
https://github.com/Shopify/theme-check/issues/553

But there's a bug preventing me from using it. :/

Maybe I'm used to having the tool automatically recognize the project root.
In this case the tool is theme-check, in other cases: Prettier, RuboCop, etc.

Perhaps you should consider doing the same? With the recent Shopify - GitHub integration (thank you! finally! 🙏), you could try using git repository root?
I understand there are many gotchas here though... :/
