### ISSUE TITLE
Theme Check Does Not Ignore Files Indicated

### ISSUE THREAD

**Issue by tomaszs** [Shopify/theme-check-vscode#76]
I have ignored files from theme-new folder, created when generating theme files, with ```.theme-check.yml```:

```ignore:
  ...
  - theme-new/
```

The folder is also ignored in .gitignore, and .themekitignore file:

```
...theme-new/
```

Where .themekitignore is indicated as ignore listing in config.yml:

```
development:
   ...
  ignores:
  - .themekitignore
```

Current result:

When I go to "theme-new" and open a file with VS Code, Theme Check starts theme validation process.

Expected result:

Theme Check ignores files ignored by config.yml, .theme-check.yml or .gitignore and does not run theme check on them and whole project.

**Comment by charlespwd** [comment]
Are you missing a `*` perhaps?

https://github.com/Shopify/theme-check/blob/main/config/default.yml#L11-L12

**Comment by charlespwd** [comment]
Closing in favour of https://github.com/Shopify/theme-check/issues/579. It's an actual issue indeed.
